### ISSUE TITLE
Magisk Script Successful but Magisk not Installed

### ISSUE THREAD

**Issue by levone1** [casualsnek/waydroid_script#3]
Using Waydroid on Sailfish OS, according to https://github.com/lal883/tama-sailfish-waydroid-instructios, and I ran Magisk script, and rebooted, and Magisk app installed, but doesn't do anything without installing  Magisk, (installation status shows "n/a"). The only method option given to install is to select and patch a file. I don't think patching Sailfish boot img would work, but not sure what other file I would patch ...

I saw note in README about it being a "bootless" installation, and that modules won't work, but as it is for me, root won't even work, and the app does nothing...

**Comment by levone1** [comment]
v. 23.0 (23000).  It started as a different version, but then I got update notification, so figured I'd rry it to see if it changed anything.

Also, when the app first opens, there's a message, "Abnormal State... not supposes to be system app..."

**Comment by levone1** [comment]
So, I went through init-magisk.sh script to try manually, and I was able to make folders and symlinks by changing permissions etc., but then I get error "/sbin/magisk not executable 32-bit elf" so seems like script installed wrong version on my phone
..

**Comment by Kabouik** [comment]
I have observed the same issue as @levone1, albeit on Droidian (I didn't try on my SFOS devices yet because none of them is up to date, and kernel modules are not there in my version). The script's `-m` option works well and does add a Magisk icon in Waydroid, but then when I open it I can't make Magisk work. If I install it as a system app, then on later launches it will complain that there was an error with it and I should set it as a user application again. I also observed what @levone1 said about patching being the only option available. I'm sorry I don't remember the details as I don't have my Droidian phone with me at the moment.

**Comment by dariox86** [comment]
Same issue on PinePhone.

**Comment by rizzini** [comment]
Same issue here. I'm on Arch x86_64.

**Comment by casualsnek** [comment]
Can you please try again to see if magisk works ?  I just pushed a small change that should make it fix this issue !

**Comment by casualsnek** [comment]
> Thanks Script ran successfully with edits, and the result is the same, except that now there is no Magisk binary... /sbin folder contains only magiskinit and magiskboot files

Can you please try again to see if magisk works ?  I just pushed a small change that should make it fix this issue !

**Comment by casualsnek** [comment]
> > can you send what does `python -c "import platform;print(platform.machine())"` return on your device ?
> 
> PinePhone running Arch Linux ARM from: https://github.com/dreemurrs-embedded/Pine64-Arch Below is what I have.
> 
> `uname -a` outputs `Linux danctnix 5.14.13-1-danctnix #1 SMP PREMPT Mon Oct 18 14:34:41 UTC 2021 aarch64 GNU/Linux`
> 
> `python -c "import platform;print(platform.machine())"` outputs `aarch64`

can you check if the correct magiskinit is copied after the latest commit ?

**Comment by levone1** [comment]
> > Thanks Script ran successfully with edits, and the result is the same, except that now there is no Magisk binary... /sbin folder contains only magiskinit and magiskboot files
> 
> Can you please try again to see if magisk works ? I just pushed a small change that should make it fix this issue !

working now, thanks. Magisk app initially opens with message "additional setup required..." and if I press "ok" it reboots, and then still shows the same message after reboot. But if I just ignore it, it works fine, and grants root.
