### ISSUE TITLE
Script uses outdated sources and GAPPS installation fails

### ISSUE THREAD

**Issue by KingWaffleIII** [casualsnek/waydroid_script#30]
The script is using sources for GAPPS which are no longer valid, causing a download error. In addition, even when manually changing the sources, the script still fails to successfully install GAPPS:

```
    ==> OpenGapps zip not downloaded or hash mismatches, downloading now .....
    100%|███████████████████████████████████████| 121M/121M [01:37<00:00, 1.24MiB/s]
    ==> Extracting opengapps...
    ==> Processing app package : /tmp/ogapps/extract/Core/vending-x86_64.tar.lz
    ==> Processing app package : /tmp/ogapps/extract/Core/vending-common.tar.lz
    Traceback (most recent call last):
      File "/home/cmdr/Downloads/waydroid_script/waydroid_extras.py", line 597, in <module>
        main()
      File "/home/cmdr/Downloads/waydroid_script/waydroid_extras.py", line 585, in main
        install_gapps()
      File "/home/cmdr/Downloads/waydroid_script/waydroid_extras.py", line 171, in install_gapps
        app_priv = os.listdir(os.path.join(extract_to, "appunpack", app_name, "nodpi"))[0]
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/ogapps/extract/appunpack/vending-common/nodpi'
```

My source: https://downloads.sourceforge.net/project/opengapps/x86_64/20220120/open_gapps-x86_64-11.0-pico-20220120.zip

**Comment by casualsnek** [comment]
Just updated the script, can you check if works asexpected, if it does please close the issue too !

**Comment by KingWaffleIII** [comment]
Hi,
I will try this but the sources are still made for Android 10, and I'm running Android 11. Will that not
cause an error?

**Comment by casualsnek** [comment]
> Hi, I will try this but the sources are still made for Android 10, and I'm running Android 11. Will that not cause an error?

No, it won't cause any errors on android 11, and apps will update themselves after installing. Script uses android 10 files since waydroid uses android 10 by default.

**Comment by KingWaffleIII** [comment]
Alright, thank you very much! The installation was successful and I can retrieve the GSF ID. One thing to note is the script reports:
```
==> Stopping waydroid and unmounting already mounted images...
==> Excepted hash: e8c9a7412f5712eea7948957a62a7d66  | File hash: 
==> Found system image: /usr/share/waydroid-extra/images/system.img
==> Resizing system image....
==> Unmounting .. 
==> Warning: umount failed.. umount: /tmp/waydroidimage: no mount point specified.
```
However, it worked so this issue is now resolved. I'll close it now.

**Comment by brccabral** [comment]
I still get the same error on newest image.
https://master.dl.sourceforge.net/project/opengapps/x86_64/20220215/open_gapps-x86_64-11.0-pico-20220215.zip

```
==> Processing app package : /tmp/ogapps/extract/Core/vending-common.tar.lz
Traceback (most recent call last):
  File "waydroid_extras.py", line 591, in <module>
    main()
  File "waydroid_extras.py", line 579, in main
    install_gapps()
  File "waydroid_extras.py", line 165, in install_gapps
    app_priv = os.listdir(os.path.join(extract_to, "appunpack", app_name, "nodpi"))[0]
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/ogapps/extract/appunpack/vending-common/nodpi'
```

**Comment by brccabral** [comment]
The one from the script too https://master.dl.sourceforge.net/project/opengapps/x86_64/20220121/open_gapps-x86_64-10.0-pico-20220121.zip

**Comment by brccabral** [comment]
Adding vending-common.tar.lz to non_apks solves the issue
